name: 打印GithubContext

on:
  workflow_call:
jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
      - name: github
        run: |
          echo "$github"

      - name: github.action
        run: |
          echo "github action: ${{ github.action }}"

      - name: github.action_path
        run: |
          echo "github action_path: ${{ github.action_path }}"

      - name: github.action_ref
        run: |
          echo "github action_ref: ${{ github.action_ref }}"

      - name: github.action_repository
        run: |
          echo "github action_repository: ${{ github.action_repository }}"

      - name: github.action_status
        run: |
          echo "github action_status: ${{ github.action_status }}"

      - name: github.actor
        run: |
          echo "github actor: ${{ github.actor }}"

      - name: github.actor_id
        run: |
          echo "github actor_id: ${{ github.actor_id }}"

      - name: github.api_url
        run: |
          echo "github api_url: ${{ github.api_url }}"

      - name: github.base_ref
        run: |
          echo "github base_ref: ${{ github.base_ref }}"

      - name: github.env
        run: |
          echo "github env: ${{ github.env }}"

      - name: github.event
        run: |
          echo "github event: ${{ github.event }}"

      - name: github.event_name
        run: |
          echo "github event_name: ${{ github.event_name }}"

      - name: github.event_path
        run: |
          echo "github event_path: ${{ github.event_path }}"

      - name: github.graphql_url
        run: |
          echo "github graphql_url: ${{ github.graphql_url }}"

      - name: github.head_ref
        run: |
          echo "github head_ref: ${{ github.head_ref }}"

      - name: github.job
        run: |
          echo "github job: ${{ github.job }}"

      - name: github.job_workflow_sha
        run: |
          echo "github job_workflow_sha: ${{ github.job_workflow_sha }}"

      - name: github.path
        run: |
          echo "github path: ${{ github.path }}"

      - name: github.ref
        run: |
          echo "github ref: ${{ github.ref }}"

      - name: github.ref_name
        run: |
          echo "github ref_name: ${{ github.ref_name }}"

      - name: github.ref_protected
        run: |
          echo "github ref_protected: ${{ github.ref_protected }}"

      - name: github.ref_type
        run: |
          echo "github ref_type: ${{ github.ref_type }}"

      - name: github.repository
        run: |
          echo "github repository: ${{ github.repository }}"

      - name: github.repository_id
        run: |
          echo "github repository_id: ${{ github.repository_id }}"

      - name: github.repository_owner
        run: |
          echo "github repository_owner: ${{ github.repository_owner }}"

      - name: github.repository_owner_id
        run: |
          echo "github repository_owner_id: ${{ github.repository_owner_id }}"

      - name: github.repositoryUrl
        run: |
          echo "github repositoryUrl: ${{ github.repositoryUrl }}"

      - name: github.retention_days
        run: |
          echo "github retention_days: ${{ github.retention_days }}"

      - name: github.run_id
        run: |
          echo "github run_id: ${{ github.run_id }}"

      - name: github.run_number
        run: |
          echo "github run_number: ${{ github.run_number }}"

      - name: github.run_attempt
        run: |
          echo "github run_attempt: ${{ github.run_attempt }}"

      - name: github.secret_source
        run: |
          echo "github secret_source: ${{ github.secret_source }}"

      - name: github.server_url
        run: |
          echo "github server_url: ${{ github.server_url }}"

      - name: github.sha
        run: |
          echo "github sha: ${{ github.sha }}"

      - name: github.token
        run: |
          echo "github token: ${{ github.token }}"

      - name: github.triggering_actor
        run: |
          echo "github triggering_actor: ${{ github.triggering_actor }}"

      - name: github.workflow
        run: |
          echo "github workflow: ${{ github.workflow }}"

      - name: github.workflow_ref
        run: |
          echo "github workflow_ref: ${{ github.workflow_ref }}"

      - name: github.workflow_sha
        run: |
          echo "github workflow_sha: ${{ github.workflow_sha }}"

      - name: github.workspace
        run: |
          echo "github workspace: ${{ github.workspace }}"