on:
  workflow_call:
    inputs:
      module_paths_v2:
        required: true
        type: string
jobs:
  generate-props:
    runs-on: ubuntu-latest
    outputs:
      publish_module_json: ${{ steps.SET-PUBLISH-MODULE-JSON.outputs.publish_module_json }}
      publish_version: ${{ steps.SET-PUBLISH-VERSION.outputs.publish_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Publish Module Json
        id: SET-PUBLISH-MODULE-JSON
        run: |
          matrix_json='${{ inputs.module_paths_v2 }}'
          echo "publish_module_json=$matrix_json" >> "$GITHUB_OUTPUT"
      - name: Set Publish Version
        id: SET-PUBLISH-VERSION
        run: |
          prev_version_1=$(grep "VERSION_NAME=" gradle.properties | sed -E 's/VERSION_NAME=([0-9]+)\.[0-9]+\.[0-9]+/\1/')
          prev_version_2=$(grep "VERSION_NAME=" gradle.properties | sed -E 's/VERSION_NAME=[0-9]+\.([0-9]+)\.[0-9]+/\1/')
          prev_version_3=$(grep "VERSION_NAME=" gradle.properties | sed -E 's/VERSION_NAME=[0-9]+\.[0-9]+\.([0-9]+)/\1/')
          formatted_version=$(printf "%s" "$prev_version_1.$prev_version_2.$prev_version_3")
          echo $prev_version_1
          echo $prev_version_2
          echo $prev_version_3
          echo $formatted_version
          echo "publish_version=$formatted_version" >> $GITHUB_OUTPUT
      - name: Send
        uses: zcong1993/actions-ding@master
        with:
          dingToken: 814b2467f4a2cd354fe6317e8bf6d2bd544f1c60bb4f1a6971d09f573306a7c6
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "title": "DangoUnit 开始打包 V${{ steps.SET-PUBLISH-VERSION.outputs.publish_version }}"
              }
            }
  dynamic-job:
    runs-on: ubuntu-latest
    needs: generate-props
    outputs:
      publish_version: ${{ needs.generate-props.outputs.publish_version }}
    strategy:
      matrix: ${{fromJson(needs.generate-props.outputs.publish_module_json)}}
    steps:
      - name: Log generate-props
        id: GENERATE-PROPS
        run: |
          echo ${{ needs.generate-props.outputs.publish_module_json }}
          echo ${{ matrix.module }}
          echo ${{ needs.generate-props.outputs.publish_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Lint
        run: |
          ./gradlew ${{ matrix.module }}:lint
      - name: Publish mavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
        run: |
          ./gradlew ${{ matrix.module }}:publish
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: arr
          path: ./${{ inputs.module_path }}build/outputs/aar/
      - name: Job fail
        continue-on-error: true
        run: |
         exit 1
  end:
    needs: dynamic-job
    runs-on: ubuntu-latest
    steps:
      - name: Log generate-props
        id: GENERATE-PROPS
        run: |
          echo ${{ needs.generate-props.outputs.publish_module_json }}
          echo ${{ matrix.module }}
          echo ${{ needs.generate-props.outputs.publish_version }}
      - name: Send
        uses: zcong1993/actions-ding@master
        with:
          dingToken: 814b2467f4a2cd354fe6317e8bf6d2bd544f1c60bb4f1a6971d09f573306a7c6
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "自动发布成功", 
                "text": "DangoUnit 发布版本 V${{ needs.dynamic-job.outputs.publish_version }}",
                "messageUrl":"https://github.com/DangoDX/DangoUnit/actions/workflows/schedule.yml"
              }
            }