on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      version_name:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 打印参数
        run: |
          export JAVA_HOME=$JAVA_HOME_17_X64
          chmod +x ./gradlew 
          ./gradlew ${{ inputs.module_path }}:assemble
          ./gradlew ${{ inputs.module_path }}:publish
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: ./lib/widget/build/outputs/aar/