on:
  workflow_call:
    inputs:
      module_paths_v2:
        required: true
        type: string
jobs:
  process_input:
    runs-on: ubuntu-latest
    steps:
      - name: Parse input string to array
        run: |
          input_string="${{ inputs.module_paths_v2 }}"
          IFS=',' read -ra my_array <<< "$input_string"
          for item in "${my_array[@]}"; do
            echo "Array item: $item"
          done
        env:
          MY_ARRAY: "${my_array[*]}"  # 将数组存储为环境变量

      - name: Upload
        run: |
          env

      - name: Upload data as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-data
          path: ${{ runner.workspace }}

  use_array:
    runs-on: ubuntu-latest
    needs: process_input
    steps:
      - name: Download data artifact
        uses: actions/download-artifact@v2
        with:
          name: my-data
          path: ${{ runner.workspace }}

      - name: Use the parsed array
        run: |
          # 在这里可以访问之前上传的数据，并使用解析后的数组
          for item in $MY_ARRAY; do
            echo "Using array item: $item"
          done