on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      version_name:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: 打印参数
        run: |
          echo "inputs.module_path = ${{ inputs.module_path }}"
          echo "inputs.artifact_name = ${{ inputs.artifact_name }}"
          echo "inputs.version_name = ${{ inputs.version_name }}"
          ls -a
          chmod +x ./gradlew && ./gradlew ${{ inputs.module_path }}:publish