on:
  workflow_call:
    inputs:
      module_paths_v2:
        required: true
        type: string
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          input_string="${{ inputs.myArrayParameter }}"
          IFS=',' read -ra my_array <<< "$input_string"
          for item in "${my_array[@]}"; do
            echo "Array item: $item"
          done
      - name: Send
        uses: zcong1993/actions-ding@master
        with:
          dingToken: 67b3d5302637555a9ef5c9ddb06b13d9d16d02fcb6fa119792154340046ea022
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "title": "action", 
                "text": "${{ inputs.module_path }}__v${{ steps.generate_version.outputs.new_version }} , 发布成功",
              }
            }