on:
  workflow_call:
    inputs:
      module_paths_v2:
        required: true
        type: string
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          # Here you can write custom logic to generate the matrix based on the previous job's output
          # For example, you can parse the output, create a JSON string representing the matrix, and set it as an output
          matrix_json='{"os": ["ubuntu-latest", "macos-latest"], "node-version": ["12", "14"]}'
          echo "::set-output name=matrix::$matrix_json"

  dynamic-job:
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}