on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo "module_path : ${{ inputs.module_path }}"
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Checkout repository
        uses: actions/checkout@v2
#      - name: Lint
#        run: |
#          module_path=$(echo "${{ inputs.module_path }}" | sed 's/\//:/g' | sed 's/^://')
#          module_path=":${module_path}"  # Add a leading colon
#          echo "Converted module path: $module_path"
#          ./gradlew ${module_path}lint
      - name: Check the current version number
        id: generate_version
        run: |
          prev_version_1=$(grep "VERSION_NAME=" ${{ inputs.module_path }}gradle.properties | sed -E 's/VERSION_NAME=([0-9]+)\.[0-9]+\.[0-9]+/\1/')
          prev_version_2=$(grep "VERSION_NAME=" ${{ inputs.module_path }}gradle.properties | sed -E 's/VERSION_NAME=[0-9]+\.([0-9]+)\.[0-9]+/\1/')
          prev_version_3=$(grep "VERSION_NAME=" ${{ inputs.module_path }}gradle.properties | sed -E 's/VERSION_NAME=[0-9]+\.[0-9]+\.([0-9]+)/\1/')
          new_version_1=$prev_version_1
          new_version_2=$prev_version_2
          new_version_3=$((prev_version_3 + 1))
          echo "current version number : $prev_version_1.$prev_version_2.$prev_version_3"
          if [ $new_version_3 -gt 999 ]; then
            new_version_2=$((new_version_2 + 1))
            new_version_3=$((new_version_3 % 1000))
            if [ $new_version_2 -gt 99 ]; then
              new_version_1=$((new_version_1 + 1))
              new_version_2=$((new_version_2 % 100))
            fi
          fi
          formatted_version=$(printf "%s" "$new_version_1.$new_version_2.$new_version_3")
          echo "new_version=$formatted_version" >> $GITHUB_OUTPUT
          echo "Formatted Versions: $formatted_version"
      - name: Modify the local version number
        run: |
          # Update the versionCode in the build file
          new_version="${{ steps.generate_version.outputs.new_version }}"
          sed -i "s/^VERSION_NAME=.*/VERSION_NAME=$new_version/" ${{ inputs.module_path }}gradle.properties
      - name: Print local version number
        run: |
          # Update the versionCode in the build file
          grep "VERSION_NAME" ${{ inputs.module_path }}gradle.properties | grep '[0-9]\+$'
#      - name: Publish mavenCentral
#        env:
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
#        run: |
#          module_path=$(echo "${{ inputs.module_path }}" | sed 's/\//:/g' | sed 's/^://')
#          module_path=":${module_path}"  # Add a leading colon
#          echo "Converted module path: $module_path"
#          ./gradlew ${module_path}publish
      - name: Push versionCode
        run: |
          git config --global --add safe.directory /__w/DangoUnit/DangoUnit
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          PREV_COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          NEW_COMMIT_MESSAGE="$PREV_COMMIT_MESSAGE -->  Update versionCode"
          git add .
          git commit -m "$NEW_COMMIT_MESSAGE"
          git pull --rebase origin master
          git push
      - name: Push tag
        run: |
          git config --global --add safe.directory /__w/DangoUnit/DangoUnit
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          module_path=$(echo "${{ inputs.module_path }}" | sed 's/\//_/g' | sed 's/_$//')
          new_tag="${module_path}_v${{ steps.generate_version.outputs.new_version }}"
          git tag $new_tag
          git pull --rebase origin master
          git push origin $new_tag
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: aar
          path: ./${{ inputs.module_path }}build/outputs/aar/