on:
  workflow_call:
    inputs:
      module_paths_v2:
        required: true
        type: string
jobs:
  generate-props:
    runs-on: ubuntu-latest
    outputs:
      publish_module_json: ${{ steps.SET-PUBLISH-MODULE-JSON.outputs.publish_module_json }}
    steps:
      - name: Set Publish Module Json
        id: SET-PUBLISH-MODULE-JSON
        run: |
          echo "publish_module_json='${{ inputs.module_paths_v2 }}'" >> "$GITHUB_OUTPUT"
  dynamic-job:
    needs: generate-props
    strategy:
      matrix: ${{fromJson(needs.generate-props.outputs.publish_module_json)}}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        run: |
          echo ${{ needs.generate-props.outputs.publish_module_json }}

  end:
    needs: dynamic-job
    runs-on: ubuntu-latest
    steps:
      - name: Send
        uses: zcong1993/actions-ding@master
        with:
          dingToken: 67b3d5302637555a9ef5c9ddb06b13d9d16d02fcb6fa119792154340046ea022
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "title": "action", 
                "text": "${{ inputs.module_path }}__v${{ steps.generate_version.outputs.new_version }} , 发布成功",
              }
            }